# Generated by Django 5.2.11 on 2026-02-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0002_servicerequest_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
