# Generated by Django 5.2.11 on 2026-02-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0004_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfl_app.servicerequest'),
        ),
    ]
