# Generated by Django 5.2.11 on 2026-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0010_project_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certifications/logos/')),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('obtenue', 'Obtenue'), ('encours', 'En cours'), ('future', 'Prévue')], max_length=20)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
