# Generated by Django 5.2.11 on 2026-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0013_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='email',
            new_name='email_sug',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='message',
            new_name='message_sug',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='name',
            new_name='name_sug',
        ),
    ]
