# Generated by Django 5.2.11 on 2026-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0014_rename_email_suggestion_email_sug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
