# Generated by Django 5.2.11 on 2026-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0016_remove_suggestion_likes_suggestionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
