# Generated by Django 5.2.11 on 2026-02-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfl_app', '0019_alter_certification_logo_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_url',
        ),
    ]
